# Generated by Django 5.1.1 on 2024-09-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
