# Generated by Django 5.1.1 on 2024-09-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
