# Generated by Django 5.1.1 on 2024-09-29 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watching_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
