# Generated by Django 5.1.1 on 2024-09-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
